name: flutter_flavorizr_example
description: A new Flutter project.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.0.2 <4.0.0'


dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2


dev_dependencies:
  flutter_flavorizr: ^2.2.1
  flutter_test:
    sdk: flutter
  
  flutter_lints: ^2.0.0




  
flavorizr:
  app:
    android:
      flavorDimensions: 'flavor-type'
    # ios vardı burada tekrar bak
  flavors:
    dev:
      app:
        name: "AppName Dev"
      android:
        applicationId: "com.example.dev"  
      ios:
        bundleId: "com.example.dev"

    prod:
      app:
        name: "AppName Prod"
      android:
        applicationId: "com.example.prod"  
      ios:
        bundleId: "com.example.prod"
    
    stagging:
      app:
        name: "AppName Stagging"
      android:
        applicationId: "com.example.stagging"  
      ios:
        bundleId: "com.example.stagging"

  

  








flutter:

  uses-material-design: true

